#!/bin/bash

echo "MALE Webcrawler v1.1" >&2
echo "USO: ./testeme <url> <profundidade> --CApath=<caminho/para/pasta/certificados>" >&2
echo "ou" >&2
echo "USO: ./testeme <url> <profundidade> --CAfile=<caminho/para/arquivo/certifica>" >&2
echo "A lista de links e salva em saida.txt" >&2
echo "" >&2
argumentos=0;
#openssl version -d | sed 's/OPENSSLDIR: "*\([a-z]*\)/\1/' | sed 's/"//'
if [ "$#" == 0 ]; then
      echo "" >&2
      echo "Ajuda" >&2
      echo "Repositorio GIT: https://github.com/andresilvaprogramador/trabalho_redes_-_webcrawler.git" >&2
      echo "Branch: ssl" >&2
      echo "" >&2
      echo "-h : esta ajuda" >&2
      echo "-c : compila binario" >&2
      echo "-i : instala bibliotecas necessarias para compilacao" >&2
else
while getopts ":hci" opt; do
  case $opt in
    h)
      echo "" >&2
      echo "Ajuda" >&2
      echo "MALE Webcrawler v1.1" >&2
      echo "Repositorio GIT: https://github.com/andresilvaprogramador/trabalho_redes_-_webcrawler.git" >&2
      echo "Branch: ssl" >&2
      echo "" >&2
      echo "-h : esta ajuda" >&2
      echo "-c : compila binario" >&2
      echo "-i : instala bibliotecas necessarias para compilacao" >&2
      ;;
    c)
      echo "Compilar webcrawler" >&2
      make
      ;;
    i)
      echo "Instalar bibliotecas necessarias pra compilacao" >&2
      sudo apt-get install libboost-regex-dev
      sudo apt-get install libssl-dev
      ;;
    \?)
      echo "Opcao invalida: -$OPTARG" >&2
      ;;
  esac
argumentos=1;
done
if [ $# = 2 ]; then
	if [ $argumentos = 0 ]; then
		./webcrawler $1 $2 > saida.txt
	fi
fi

if [ $# = 3 ]; then
	if [ $argumentos = 0 ]; then
		./webcrawler $1 $2 $3 > saida.txt
	fi
fi

fi
